// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWWd7uREhyiwV-5Ku9w8uNnGU6N4-YxPY',
    appId: '1:932012401488:web:e74c969eb053f07d29c255',
    messagingSenderId: '932012401488',
    projectId: 'flutter-messenger-app-a807f',
    authDomain: 'flutter-messenger-app-a807f.firebaseapp.com',
    storageBucket: 'flutter-messenger-app-a807f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQa2j4ossbIXh92ep224GBkJsKAxvHyYw',
    appId: '1:932012401488:android:a7ce6b45f74744ca29c255',
    messagingSenderId: '932012401488',
    projectId: 'flutter-messenger-app-a807f',
    storageBucket: 'flutter-messenger-app-a807f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbs064AyH8ju4FZOL_NxB54lVcwgtCslA',
    appId: '1:932012401488:ios:1e247a5b7cf3a90c29c255',
    messagingSenderId: '932012401488',
    projectId: 'flutter-messenger-app-a807f',
    storageBucket: 'flutter-messenger-app-a807f.appspot.com',
    iosBundleId: 'com.example.flutterMessengerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbs064AyH8ju4FZOL_NxB54lVcwgtCslA',
    appId: '1:932012401488:ios:fc1a85365bc3709629c255',
    messagingSenderId: '932012401488',
    projectId: 'flutter-messenger-app-a807f',
    storageBucket: 'flutter-messenger-app-a807f.appspot.com',
    iosBundleId: 'com.example.flutterMessengerApp.RunnerTests',
  );
}
